backend:
  name: git-gateway
  branch: master

media_folder: "_site/public/img/uploads"
public_folder: "public/img/uploads"

collections:
  - name: "posts"
    label: "Posts"
    create: true
    folder: "input/posts"
    slug: "{{ slug }}"
    fields: 
      - { label: "Layout", name: "layout", widget: "hidden", default: "basic/base.njk"}
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Description", name: "description", widget: "string"}
      - { label: "Post Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name : "featuredImage", widget: "image"}
